### PR TITLE
Adds `future.send(to: Websocket)`

### PR DESCRIPTION
**Pull request by twof**
Should ease the integration of Websockets into promise chains. Websockets don't mesh well with futures in general right now, but these convenience functions ought to help a bit.

Example usage:
```
router.websocket("message") { (req, websocket) in
    websocket.onString { (ws, msg) in
        let decoder = JSONDecoder()
        let encoder = JSONEncoder()
        let message = try decoder.decode(Message.self, from: msg.data(using: .utf8)!)
        
        req.withPooledConnection(to: .psql, closure: { (conn) in
            return conn
                .query(Message.self)
                .save(message)
                .flatMap(to: [Message].self) { (_) -> Future<[Message]> in
                    return conn.query(Message.self).all()
                }.map(to: String.self) { (allMessages) in
                    guard let allJSONMessages = try encoder.encode(allMessages).toString()
                        else {throw Abort(.internalServerError)}
                    return allJSONMessages
                }.send(to: ws) // This is the addition
                .catch({ (err) in
                    print(err)
                })
        })
    }
}
```

### CODE REVIEW

**Comment by Joannis** [comment]
I don't want to clutter the future namespace. But `ws.send(future)` makes sense. I think we should be able to send `Data` over the text channel, too.

**Comment by twof** [comment]
Oh yeah that might be better. It would also be nice if you could send Content via a websocket and have it converted to JSON automatically like you can via HTTP. I don't know if that's bad practice or anything though.

**Comment by Joannis** [comment]
I think a helper in **Vapor** would be nice such as `websocket.send(json: myModel)`. You can't assume that everyone will be communicating JSON here.

**Comment by twof** [comment]
Closing. Opening new PRs with suggested changes

**Comment by twof** [comment]
`ws.send(future)`: https://github.com/vapor/engine/pull/234

**Pull request closed without merging**
