### PR TITLE
solve empty stream error

### PR DESCRIPTION
**Pull request by tannernelson**
Solves vapor/vapor#523

I did some detective work and figured out what was causing the empty stream error. It's coming from any client that doesn't send `connection: close`. After one or more request/response pairs have been sent over the wire, the server will loop back over on the respond loop and sit on `readLine()` in the request parser. It will sit on this forever until there is a new HTTP line.

For some reason, it appears that after ~30 seconds (not from Socks timeout) Safari or c sockets or something starts sending 0 length byte arrays. The stream will only ever send empty arrays after this point. So basically if we get an empty stream error that means we need to close it--it's done giving us useful data.

@czechboy0 maybe you might have more insight onto why `recv` is returning a byte array with 0 length instead of a timeout error. When I tried setting a timeout of 30 seconds on `receivingTimeout`, it was successfully timing out, but with a strange error `code 35 ("Resource deadlock avoided")` Is `35` the correct error code for this and just a misleading error message? If so, using the timeouts here might be a more robust solution.

```
Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))
```

Either way, this seems to fix the issue and the added `defer` statement ensures streams are getting closed even in the case of an error.

### CODE REVIEW

**Comment by czechboy0** [comment]
Are we sure that the zero byte arrays aren't just how keep alive is manifesting itself? I'm genuinely asking, I'm not sure.

**Comment by czechboy0** [comment]
Re the error code, probably a confusing message, but yeah I think that's expected behavior.

**Comment by tannernelson** [comment]
Awesome detective work haha.

> 0 - no bytes returned means the client closed the connection.

Good to know! I'll merge this, then.

Did you find out anything about error 35 when adding timeouts?

**Comment by czechboy0** [comment]
Not yet, but I think it's expected.

**Pull request merged**
