### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by Joannis**
Adds tests and fixes a few unfound bugs

### CODE REVIEW

**Comment by tanner0101** [comment]
What's the status on this one?

**Comment by Joannis** [comment]
This one is good to go, although it'll need your review @tanner0101

**Comment by tanner0101** [comment]
Closing for inactivity. Let's re-open if you want to fix merge conflict + tests and merge this through.

**Comment by Joannis** [comment]
I'm not going to fix these tests until #231 is fixed. Leaving out security tests for the sake of passing tests doesn't seem sensible to me 😂

**Comment by Joannis** [comment]
So my conclusion is that the security is implemented properly, but no control hooks are in place anymore to configure the maximum memory usage.

**Comment by tanner0101** [comment]
once tests are passing i'll review 👍

**Pull request closed without merging**
