### PR TITLE
Recreate stream on ParserError.streamEmpty error

### PR DESCRIPTION
**Pull request by sroebert**
A the `Client` only creates a single stream for a connection, once this connection is closed, the client will not be able to make any more requests and will return a `ParserError.streamEmpty` error. In this case, creating a new stream would solve the issue.

### CODE REVIEW

**Comment by sroebert** [comment]
Too be honest, I'm not sure this is the right solution or if this is a problem with the server I'm connecting to, this seemed to help though.

**Comment by andreasley** [comment]
It's a very specific solution. We might want to consider a more generic "retry x times" approach for different kinds of errors - or handle such errors in the calling code altogether.

**Comment by sroebert** [comment]
For now I switched to using the `FoundationClient`, which does not seem to suffer from these issues. This is also why I do not think it should be handled by the calling code, considering the calling code it not responsible for managing the connection.

**Comment by tannernelson** [comment]
The client was purposefully designed to create one connection (for performance reasons). If you want to create a new connection for each request, then call the static methods instead. Those will generate a new instance of the Client for each call.

**Comment by sroebert** [comment]
Ah ok, this then differs from the `FoundationClient`, which keeps the connection open, but automatically creates a new one when necessary. I will use that one I instead for now then.

**Pull request closed without merging**
