### PR TITLE
Add methods to append and remove path components from URIs

### PR DESCRIPTION
**Pull request by harlanhaskins**
Adds `appendingPathComponent`, `deletingLastPathComponent`, and `removingPath` to the public API for `URI`.

### CODE REVIEW

**Comment by tannernelson** [comment]
@LoganWright can you please review?

**Comment by harlanhaskins** [comment]
@tannernelson Thanks! What would you recommend for the comments?

**Comment by tannernelson** [comment]
```swift
/**
    Lorem ipsum dolor sit amet.

    @param bar Consectetur adipisicing elit.

    @return Sed do eiusmod tempor.
*/
func foo(bar: String) -> AnyObject { ... }
```

From:
http://nshipster.com/swift-documentation/

**Comment by harlanhaskins** [comment]
Interesting. I was going by [Apple's Markup guide](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/AddingMarkup.html#//apple_ref/doc/uid/TP40016497-CH100-SW1), but I'll update them. Any concerns with the wording?

**Comment by tannernelson** [comment]
Thanks!

**Comment by harlanhaskins** [comment]
🎉🎉🎉

**Comment by harlanhaskins** [comment]
This is gonna make it much nicer to redirect to other pages in your site. Thanks!

**Pull request merged**
