### PR TITLE
Complete status code and header fields.

### PR DESCRIPTION
**Pull request by chinsyo**
Reference 
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

### CODE REVIEW

**Comment by tanner0101** [comment]
unfortunately we can't add cases to a public enum (as it's a breaking change). we could take the additional header fields, but the status codes will have to wait until 3.0

**Comment by chinsyo** [comment]
Fine. 🤝

**Comment by chinsyo** [comment]
@tanner0101 Any news?

**Comment by tanner0101** [comment]
would you mind creating this as a PR to https://github.com/vapor/vapor/tree/beta? the new http module is currently in vapor/vapor:beta while in development. that way we can include these breaking changes in 3.0. thanks!

**Comment by chinsyo** [comment]
OK, I'll do it.

**Pull request closed without merging**
